### ISSUE TITLE
Project ERROR: qmmp-1 development package not found

### ISSUE THREAD

**Issue by paulsybrandy** [TTK-qmmp/qmmp-flowwave#1]
Upon initiating the 'qmake' command, I get the following error straightaway:

Info: creating stash file /home/neocube/qmmp-flowwave/.qmake.stash
Project ERROR: qmmp-1 development package not found

But I cannot seem to find this package it is halfway referring to. Any help would be greatly appreciated. 

System information:

OS: Kubuntu 22.10 x86_64
Host: Inspiron 5400 AIO
Kernel: Linux 5.19.0-31-generic
Shell: /bin/bash 5.2.2
DE: Plasma 5.25.5
WM: KWin
CPU: 11th Gen Intel i7-1165G7 (8)
GPU: Intel TigerLake-LP GT2 [Iris Xe
Memory: 6817MiB / 15633MiB (43%)
GPU Driver: Dell TigerLake-LP GT2

Thank you in advance.

**Comment by Greedysky** [comment]
This is a plugin of qmmp, you should install qmmp player first.

**Comment by paulsybrandy** [comment]
So yeah... I already have it installed. Hence the reason I am now looking for extras to enhance it. But thank you.

**Comment by Greedysky** [comment]
Which version you have been installed? Just install 1.6.x for Qt5, and version for Qt6 is not available now.

**Comment by paulsybrandy** [comment]
I have Version: 1.4.4 installed usging Qt5.15.6, compiled with Qt5.15.4

**Comment by Greedysky** [comment]
Sorry, version less than 1.6.0 is no longer supported.

**Comment by paulsybrandy** [comment]
Ah, gotcha. Alright, well thank you for informing me. I shall mark it as closed.
